### ISSUE TITLE
Add support to fetch  user settings 

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-azuread#101]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

Requirement CIS 2.0.0 > `1.3 Ensure that 'Users can create Azure AD Tenants' is set to 'No'`

![image](https://user-images.githubusercontent.com/26873346/224666503-7b4c1d08-5349-43d8-8db4-3f618b36577f.png)

**Comment by karanpopat** [comment]
As per CIS 2.0.0 > 1.3

> Please note that at this point of time, there is no Azure CLI or other API commands
> available to programmatically conduct security assessment for this recommendation.
