### ISSUE TITLE
Add support to fetch user consent settings

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-azuread#102]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

Requirement - CIS v2.0.0 > 1.11 Ensure `User consent for applications` is set to `Do not allow user consent` 

![image](https://user-images.githubusercontent.com/26873346/224697138-3cdfaa11-02ff-4038-bbd1-074992af391a.png)

**Comment by karanpopat** [comment]
No API at this moment to fetch user consent settings
