### ISSUE TITLE
AzureAD plugin - Error: null (SQLSTATE HV000)

### ISSUE THREAD

**Issue by shayc12** [turbot/steampipe-plugin-azuread#107]
While configuring Service Principle at:
 .steampipe/config/azuread.spc

And try to run ant query:
> select display_name, user_principal_name, user_type from azuread_user where id = '34ce1cea-432e-4f00-a329-4da071d044b2';

The result:
Error: null (SQLSTATE HV000)

Same credential  working on Azure Plugin

**Comment by misraved** [comment]
Welcome to Steampipe @shayc12 and apologies for the bump!!

Do you get this error only for the `azuread_user` table or do you see the error across all the tables?

Also, could you also share a snapshot of your `.steampipe/config/azuread.spc` file removing the sensitive information?

**Comment by misraved** [comment]
@shayc12 could you also check if the user has all the permissions mentioned in https://github.com/turbot/steampipe-plugin-azuread/blob/main/docs/index.md#credentials

**Comment by cbruno10** [comment]
Related Slack thread - https://steampipe.slack.com/archives/C01UECB59A7/p1681814878183999

**Comment by bigdatasourav** [comment]
Hey @shayc12, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
