### ISSUE TITLE
Fix column type of column `tags` in table `azuread_group`

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-plugin-azuread#110]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-azuread/pull/111
