### ISSUE TITLE
Unable to query AZUREUSGOVERNMENTCLOUD sovereign cloud tenant

### ISSUE THREAD

**Issue by bryanburke** [turbot/steampipe-plugin-azuread#125]
**Describe the bug**

I am unable to query any Azure AD tables in an `AZUREUSGOVERNMENTCLOUD` sovereign cloud tenant. I tried both Azure CLI and service principal client ID and secret for authentication. I can confirm I have the necessary permissions, and Azure CLI commands such as `az ad user list` work.

The specific error I receive when querying any table is:

> response cannot be nil

Steampipe then produces an empty result set.

I have attached my `azuread.scp` config file and logs from running a query with `STEAMPIPE_LOG_LEVEL=DEBUG`.

[azuread.spc.txt](https://github.com/turbot/steampipe-plugin-azuread/files/12242332/azuread.spc.txt) (renamed to .txt to allow for GH upload)

[database-2023-08-02.log](https://github.com/turbot/steampipe-plugin-azuread/files/12242336/database-2023-08-02.log)

[plugin-2023-08-02.log](https://github.com/turbot/steampipe-plugin-azuread/files/12242338/plugin-2023-08-02.log)

**Steampipe version (`steampipe -v`)**

v0.20.9

**Plugin version (`steampipe plugin list`)**

v0.12.0

**To reproduce**

1. Authenticate Azure CLI with an Azure US Government tenant. Example:

   ```sh
   az cloud set --name AzureUSGovernment
   az login --tenant TENANT_ID_HERE
   ```

1. Create the `~/.steampipe/config/azuread.spc` file as attached.

1. Run any query. Example from docs:

   ```sh
   steampipe query 'SELECT display_name, user_principal_name, user_type FROM azuread_user;'
   ```

**Comment by rajlearner17** [comment]
@bryanburke, Thanks for using Steampipe!
 
Sad to see this this blocked you. You have provided a good set of information to start with. We will investigate this and revert.

**Comment by ParthaI** [comment]
@bryanburke, we appreciate your diligence in bringing this issue to our attention. We have successfully replicated the problem on our side. At the moment, we are actively investigating the matter and will certainly keep you informed as soon as we arrive at a resolution. Your patience is greatly appreciated. Thank you!

**Comment by ParthaI** [comment]
@bryanburke, just a quick update: we have gone ahead and raised an issue on the SDK side addressing this matter. Our plan is to continue our efforts once we've received feedback on that front. Thank you for your understanding!

Issue ref: https://github.com/microsoftgraph/msgraph-sdk-go/issues/552

**Comment by cbruno10** [comment]
Hi @bryanburke , I believe we're still blocked on https://github.com/microsoftgraph/msgraph-sdk-go/issues/552, which hasn't received a response yet. I'm closing this issue but we will re-open once we receive more info in the SDK issue.

If you have any other questions, please let us know!

**Comment by bryanburke** [comment]
@cbruno10 @ParthaI I can confirm this issue still occurs on the latest version of the plugin (v1.2.0). I believe I might see the cause.

When the plugin initializes the Graph client, it accounts for Azure China sovereign cloud in two ways:

1. Overrides `scopes` to the `.default` scope for Azure China: <https://github.com/turbot/steampipe-plugin-azuread/blob/v1.2.0/azuread/service.go#L170-L173>
2. Overrides `baseUrl` to the API endpoint for Azure China: <https://github.com/turbot/steampipe-plugin-azuread/blob/v1.2.0/azuread/service.go#L187-L189>

It does not, however, account for Azure US Government sovereign cloud in these same ways.

The domain for Azure US Government Graph API is: `graph.microsoft.us`

<https://learn.microsoft.com/en-us/graph/deployments#microsoft-graph-and-graph-explorer-service-root-endpoints>

So the scope for Azure US Government is: `https://graph.microsoft.us/.default`

And the API endpoint base URL is: `https://graph.microsoft.us/v1.0`
