### ISSUE TITLE
Rename the plugin to Entra ID

### ISSUE THREAD

**Issue by misraved** [turbot/steampipe-plugin-azuread#133]
**Is your feature request related to a problem? Please describe.**
Microsoft recently renamed the Azure AD to Microsoft Entra ID. 

**Describe the solution you'd like**
The plugin needs to be renamed to use Entra ID instead of Azure AD.

**Describe alternatives you've considered**

**Additional context**
https://learn.microsoft.com/en-gb/azure/active-directory/fundamentals/new-name

**Comment by cbruno10** [comment]
I think we'd probably deprecate this plugin and create a new plugin with a new plugin name, new table names, etc., to allow for a clean switch and to avoid breaking changes in users' queries and our mods (similar to what we had done for the Turbot Guardrails plugin).
