### ISSUE TITLE
MFA status field for user

### ISSUE THREAD

**Issue by albertwilliamsxyz** [turbot/steampipe-plugin-azuread#155]
**Is your feature request related to a problem? Please describe.**
I have a case for which I need to validate whether or not there are users for which mfa is not enabled / enforced and get those users. The thing is that AFAIK there are 3 different ways to setup MFA, enabling default security settings, assigning groups and/or users to an access control policy enforcing MFA, and also per-user MFA which is a view in the console that lets you change that state manually

**Describe the solution you'd like**
To have a column dedicated to mfa in user.

**Describe alternatives you've considered**

**Additional context**

**Comment by rajlearner17** [comment]
@albertwilliamsxyz, Thanks for using Steampipe! 

I appreciate raising this issue while we are rechecking the feasibility, if there is any direct way to check this MFA for each user through API or not. 

As you mentioned, there are a few ways to set MFA in Azure AD users. Have you looked into [this query](https://hub.steampipe.io/mods/turbot/azure_compliance/queries/iam_conditional_access_mfa_enabled) 

Please share your feedback.

**Comment by ParthaI** [comment]
Hello @albertwilliamsxyz, during my investigation into this issue, I've made several observations, which I'm outlining below:

- A user may possess various authentication methods, such as Email and Phone. More details on these can be found [here](https://learn.microsoft.com/en-gb/graph/api/resources/authenticationmethod?view=graph-rest-1.0).
- There is an [API available](https://learn.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&tabs=http) that enables us to retrieve the authentication methods registered for users.
- After updating our existing code in the table `azuread_user`, I am now able to extract these authentication method details for a user successfully.

![Screenshot 2023-11-15 at 4 34 18 PM](https://github.com/turbot/steampipe-plugin-azuread/assets/47887552/3cd300ed-3422-4826-a422-fb2c112be38d)

```
select display_name, jsonb_pretty(authentication_methods) from azuread_user where display_name = 'test'
+--------------+-----------------------------------------------------------------------+
| display_name | jsonb_pretty                                                          |
+--------------+-----------------------------------------------------------------------+
| test         | [                                                                     |
|              |     {                                                                 |
|              |         "ID": "weqdwwwd-wqqw-4051-897c-xzxasadsadwwq,                 |
|              |         "OdataType": "#microsoft.graph.phoneAuthenticationMethod",    |
|              |         "AdditionalData": {                                           |
|              |         }                                                             |
|              |     },                                                                |
|              |     {                                                                 |
|              |         "ID": "342g4323-6103-485e-b985-gdssdewraaaa",                 |
|              |         "OdataType": "#microsoft.graph.passwordAuthenticationMethod", |
|              |         "AdditionalData": {                                           |
|              |         }                                                             |
|              |     },                                                                |
|              |     {                                                                 |
|              |         "ID": "3gggge32-3445-446f-83cc-35t223g33223",                 |
|              |         "OdataType": "#microsoft.graph.emailAuthenticationMethod",    |
|              |         "AdditionalData": {                                           |
|              |         }                                                             |
|              |     }                                                                 |
|              | ]                                                                     |
+--------------+-----------------------------------------------------------------------+
```

Just to confirm, were you seeking that data for a specific user? or Is there anything else you are looking for?

Thank you!

**Comment by ParthaI** [comment]
Hi @albertwilliamsxyz, I hope you are doing well. Did you get a chance to look at the above issue comment? 

Your feedback would be highly appreciated, Thanks!

**Comment by ParthaI** [comment]
Hello @albertwilliamsxyz, I trust you're well. Have you had the opportunity to review the recent comment regarding the issue we discussed?

**Comment by ParthaI** [comment]
Hi @albertwilliamsxyz, as we haven't received any updates from you for a while, we are going to close this issue for now. However, please don't hesitate to reopen it if further assistance is needed. Thank you!
