### ISSUE TITLE
Fix column "password_profile" does not exist

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-azuread#17]
**Describe the bug**
```
> select display_name, password_profile from azure_ad_user
Error: column "password_profile" does not exist
```
**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by cbruno10** [comment]
@rajlearner17 Do we have this column in an example somewhere? Also, the table name you have in your query is from the `azure` plugin, not the `azuread` plugin, so I'm not sure what this bug is referring to. Can you please add more details? Thanks!

**Comment by ParthaI** [comment]
This issue is not relate to `azuread` plugin this is relate to `azure` plugin, so closing this.
