### ISSUE TITLE
"Error: interfaceToColumnValue failed for column 'on_premises_net_bios_name': found X, expected number"

### ISSUE THREAD

**Issue by yooakim** [turbot/steampipe-plugin-azuread#24]
Using this query:

    select * from azuread.azuread_group

returns this error:

    Error: interfaceToColumnValue failed for column 'on_premises_net_bios_name': found X, expected number

v0.8.0

**Plugin version (`steampipe plugin list`)**
```
❯ steampipe plugin list
+--------------------------------------------------+---------+-------------+
| Name                                             | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/azure@latest     | 0.18.0  | azure       |
| hub.steampipe.io/plugins/turbot/azuread@latest   | 0.0.1   | azuread     |
| hub.steampipe.io/plugins/turbot/github@latest    | 0.6.0   | github      |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.1.3   | steampipe
```

**To reproduce**
Execute the query shown above

**Expected behavior**
Expected to get a list of groups from our Azure AD

**Comment by e-gineer** [comment]
Thanks for reporting this @yooakim - really appreciate your feedback and testing - it's hard to find all the edges of these environments in small, demo environments!

I suspect the column type is wrong:

https://github.com/turbot/steampipe-plugin-azuread/blob/main/azuread/table_azuread_group.go#L61

We should be expecting a STRING, not a TIMESTAMP.
