### ISSUE TITLE
issue with azuread_group

### ISSUE THREAD

**Issue by elasticdotventures** [turbot/steampipe-plugin-azuread#27]
**Describe the bug**

steampipe query "select
>   display_name,
>   id,
>   description,
>   mail
> from
>   azuread_group;"
Warning: executeQueries: query 1 of 1 failed: pq: rpc error: code = Unknown desc = interfaceToColumnValue failed for column 'on_premises_net_bios_name': found P, expected number

**Steampipe version (`steampipe -v`)**
0.8.2

**Plugin version (`steampipe plugin list`)**
0.0.1

**To reproduce**
^^^

**Expected behavior**

**Additional context**

**Comment by bigdatasourav** [comment]
@elasticdotventures new azuread plugin version released. https://github.com/turbot/steampipe-plugin-azuread/blob/v0.0.2/CHANGELOG.md#v002-2021-09-28
