### ISSUE TITLE
Add intune support to Azure AD devices table

### ISSUE THREAD

**Issue by chrichts** [turbot/steampipe-plugin-azuread#82]
M365/AzureAD have a lot of overlap between AzureAD and intune. From a pure architecture perspective, it looks like intune managed devices are still tracked in Azure AD as devices but with property type as managed. Additionally, intune managed devices have a lot more data that non-managed devices. 

Just from the architectural perspective, I think it makes sense to add intune support to the Azure AD Devices table. I'll take an initial crack at it and see what I can come up with.

**Comment by cbruno10** [comment]
Hey @chrichts , for Intune, do you know if they have their own APIs? Also, is there a separate console/UI where you can only manage Intune resources?

Beside devices, are there particular resources in Intune you find yourself using frequently?

I haven't had an opportunity to use Intune really (just Azure AD + Microsoft 365), so I'm not that familiar with it, but I am interested in adding support for it, either in this plugin or potentially a new one.
