### ISSUE TITLE
Risky IP / azuread_sign_in_report error

### ISSUE THREAD

**Issue by Bobaero** [turbot/steampipe-plugin-azuread#94]
**Describe the bug**
In the Azure SignIn Report, IP Address can be "risky", if so, the IP address contains some "X", and azuread failed with the following error : 
select * from azuread_sign_in_report;
Warning: executeQueries: query 1 of 1 failed: ERROR: rpc error: code = Unknown desc = ip_address: invalid ip address [DELETED].XX  (SQLSTATE HV000)

More documentation : https://learn.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-health-adfs-risky-ip

Note : [DELETED] is the first 3 parts of a normal IP Address.

**Steampipe version (`steampipe -v`)**
Example: v0.16.4

**Plugin version (`steampipe plugin list`)**
Example: v0.8.1

Many thanks for your help !

**Comment by Subhajit97** [comment]
Hi @Bobaero, welcome to Steampipe! Sorry to see that you are running into issues.
Appreciate the extra information; it really helps!
I have pushed a commit addressing the above issue: https://github.com/turbot/steampipe-plugin-azuread/pull/95

If possible, can you please refer to this PR to validate whether the changes resolve the error?

You can use the below steps to build the plugin locally:
- Clone the repo: `git clone https://github.com/turbot/steampipe-plugin-azuread.git`
- Go to the directory: `cd steampipe-plugin-azuread`
- Go to the branch: `git checkout issue-94`
- Run `make`
- Then try `steampipe query`

Let us know if you need any help. Thanks!

**Comment by Bobaero** [comment]
Hi @Subhajit97 ,

First, it's me who thanks you for your time ! You've doing a great job and my Azure AD bring bugs which you can't detect until someone get it :D 

I've tried to make the issue-94 branche but i can't build as i get the following error : 
build github.com/Azure/azure-sdk-for-go/sdk/azcore: cannot load github.com/Azure/azure-sdk-for-go/sdk/azcore: no Go source files

Can you point me the must have go modules ?

Many thanks !

**Comment by Bobaero** [comment]
Hum, I'm using Ubuntu on Windows through WSL2.0 and i can only update golang-go to the 1.13.8 linux/amd64 through apt install.

go mod tidy failed with an error : 
**runtime/metrics: malformed module path "runtime/metrics": missing dot in first path element**

I'll try to find a way to update my go version.

**Comment by Bobaero** [comment]
Ok, with go 1.19, things are going smoothly, i'm waiting for the make to complete.

**Comment by Bobaero** [comment]
And it's working ! No more error due to IP address ! 

Many thanks !!!

**Comment by Subhajit97** [comment]
Great! Thanks again, @Bobaero, for helping out in testing so quickly. Glad the fix worked for you! We have released a new Azure AD plugin version, `v0.8.3`, including this fix.
